# Understanding Matrices

### 1.1 Creating Matrix

in numpy

In [1]:
import numpy as np

In [5]:
np.array([[1, 2],
          [3, 4]])

array([[1, 2],
       [3, 4]])

in pytorch

In [6]:
import torch

In [9]:
torch.Tensor([[1, 2], [3, 4]])

tensor([[1., 2.],
        [3., 4.]])

### 1.2 Creating matrix with default value

In [10]:
np.ones([2, 2])

array([[1., 1.],
       [1., 1.]])

In [12]:
torch.ones([2, 3])

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [13]:
np.random.rand(2, 3)

array([[0.08258709, 0.0210752 , 0.4989796 ],
       [0.94822249, 0.05776788, 0.04907456]])

In [14]:
torch.rand(2, 2)

tensor([[0.7142, 0.5190],
        [0.1710, 0.9420]])

### 1. 3 Seeds for Reproducibility

In [16]:
np.random.seed(0)
np.random.rand(2, 2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [20]:
np.random.seed(0)
np.random.rand(2, 2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [18]:
torch.manual_seed(0)
torch.rand(2,2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [22]:
torch.manual_seed(0)
torch.rand(2,2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

### 1. 4 Numpy to Torch (and datatype)

In [24]:
np_array = np.ones([2, 2])
np_array

array([[1., 1.],
       [1., 1.]])

In [25]:
type(np_array)

numpy.ndarray

In [26]:
torch_tensor = torch.from_numpy(np_array)
torch_tensor

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

In [27]:
type(torch_tensor)

torch.Tensor

In [31]:
np_array_new = np.ones([2,2], dtype=np.int64)
print(torch.from_numpy(np_array_new))
print(torch.from_numpy(np_array_new).type())

tensor([[1, 1],
        [1, 1]])
torch.LongTensor


In [33]:
np_array_new = np.ones([2,2], dtype=np.int32)
print(torch.from_numpy(np_array_new))
print(torch.from_numpy(np_array_new).type())

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)
torch.IntTensor


In [34]:
np_array_new = np.ones([2,2], dtype=np.uint8)
print(torch.from_numpy(np_array_new))
print(torch.from_numpy(np_array_new).type())

tensor([[1, 1],
        [1, 1]], dtype=torch.uint8)
torch.ByteTensor


In [35]:
np_array_new = np.ones([2,2], dtype=np.float64)
print(torch.from_numpy(np_array_new))
print(torch.from_numpy(np_array_new).type())

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)
torch.DoubleTensor


In [36]:
np_array_new = np.ones([2,2], dtype=np.float32)
print(torch.from_numpy(np_array_new))
print(torch.from_numpy(np_array_new).type())

tensor([[1., 1.],
        [1., 1.]])
torch.FloatTensor


In [37]:
np_array_new = np.ones([2,2], dtype=np.double)
print(torch.from_numpy(np_array_new))
print(torch.from_numpy(np_array_new).type())

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)
torch.DoubleTensor


### 1.5 Torch to Numpy

In [41]:
torch_tensor = torch.ones([3, 3])
print(torch_tensor)
print(torch_tensor.type())

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.FloatTensor


In [42]:
torch_to_numpy = torch_tensor.numpy()

In [43]:
torch_to_numpy

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

### 1.5 Resizing Tensor

#### Changing Shape of Tensor

In [64]:
a = torch.ones(2, 2)

In [65]:
a.size()

torch.Size([2, 2])

In [68]:
a.view(4)

tensor([1., 1., 1., 1.])

#### Element-wise Addition

In [69]:
b = torch.ones(2,2)
b

tensor([[1., 1.],
        [1., 1.]])

In [70]:
c = a + b

In [71]:
c

tensor([[2., 2.],
        [2., 2.]])

In [72]:
d = torch.add(a, b)

In [73]:
d

tensor([[2., 2.],
        [2., 2.]])

#### Addition

In [74]:
c

tensor([[2., 2.],
        [2., 2.]])

In [75]:
c + a

tensor([[3., 3.],
        [3., 3.]])

In [76]:
c

tensor([[2., 2.],
        [2., 2.]])

In [77]:
c.add_(a)   # inplace operation

tensor([[3., 3.],
        [3., 3.]])

In [78]:
c

tensor([[3., 3.],
        [3., 3.]])

#### Subtraction

In [79]:
a - b

tensor([[0., 0.],
        [0., 0.]])

In [80]:
a

tensor([[1., 1.],
        [1., 1.]])

In [82]:
a.sub(b)

tensor([[0., 0.],
        [0., 0.]])

In [81]:
b

tensor([[1., 1.],
        [1., 1.]])

In [84]:
a.sub_(b)   # inplace operation

tensor([[0., 0.],
        [0., 0.]])

In [85]:
a

tensor([[0., 0.],
        [0., 0.]])

#### Multiplication

In [87]:
b

tensor([[1., 1.],
        [1., 1.]])

In [88]:
c

tensor([[3., 3.],
        [3., 3.]])

In [86]:
b * c

tensor([[3., 3.],
        [3., 3.]])

In [89]:
b

tensor([[1., 1.],
        [1., 1.]])

In [92]:
b.mul_(c)

tensor([[3., 3.],
        [3., 3.]])

In [93]:
b

tensor([[3., 3.],
        [3., 3.]])

#### Division

In [96]:
d = torch.Tensor([[6, 6], [4, 4]])
e = torch.Tensor([[2, 2], [2, 2]])

In [97]:
d / e

tensor([[3., 3.],
        [2., 2.]])

In [99]:
torch.div(d, e)

tensor([[3., 3.],
        [2., 2.]])

In [100]:
d.div_(e)

tensor([[3., 3.],
        [2., 2.]])

In [101]:
d

tensor([[3., 3.],
        [2., 2.]])

#### Mean

In [104]:
f = torch.Tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
f.size()

torch.Size([10])

In [105]:
f.mean(dim=0)   #dim = dimension starting from 0

tensor(5.5000)

In [109]:
f.mean(dim=1)

RuntimeError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [106]:
g = torch.Tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 
                  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])

In [107]:
g.size()

torch.Size([2, 10])

In [108]:
g.mean(dim=1)

tensor([5.5000, 5.5000])

### Standard Deviation

In [110]:
h = torch.Tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
h.std(dim=0)

tensor(3.0277)