### 2.1 variable

Variable wraps Tensors and allow accumulating Gradient. (...What?)

And in order to create variable with PyTorch, we need to import extra

In [1]:
import torch
from torch.autograd import Variable

In [2]:
a = Variable(torch.ones(2, 2), requires_grad=True)
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [5]:
b = Variable(torch.ones(2, 2), requires_grad=True)
print(a + b)

tensor([[2., 2.],
        [2., 2.]], grad_fn=<ThAddBackward>)


In [4]:
print(torch.add(a, b))

tensor([[2., 2.],
        [2., 2.]], grad_fn=<ThAddBackward>)


In [6]:
print(a * b)

tensor([[1., 1.],
        [1., 1.]], grad_fn=<ThMulBackward>)


In [7]:
print(torch.mul(a, b))

tensor([[1., 1.],
        [1., 1.]], grad_fn=<ThMulBackward>)


### 2.2 Gradient

Accumulating Gradient...?

Let's caculate the equation in PyTorch

$$y_i = 5(x_i + 1)^2$$

In [28]:
x = Variable(torch.ones(2), requires_grad=True)
x

tensor([1., 1.], requires_grad=True)

$$y_i | _{x_i=1}  = 5(1+1)^2 = 5(2)^2 = 5(4) = 20$$

In [29]:
y = 5 * (x + 1) ** 2
y

tensor([20., 20.], grad_fn=<MulBackward>)

To calcuate backward should be called only on a scalar. Which means, we need to reduce the output we have to a single value (1-element tensor).

$$o = \frac{1}{2} \sum y_i$$

In [30]:
o = (1/2) * torch.sum(y)
o

tensor(20., grad_fn=<MulBackward>)

### Recap

`y` equation : $y_i = 5(x_i + 1)^2$  

`o` equation : $o = \frac{1}2 \sum y_i$

<br>
<br>

**Rewrite `o` eqation ...**

$$o = \frac{1}2 \sum 5(x_i + 1)^2$$

<br>

$$\frac{\partial o}{\partial x_i} = \frac{1}{2}[10(x_i+1)]$$

$$\frac{\partial o}{\partial x_i}| _{x_i=1} = \frac{1}{2}[10(1+1)] = \frac{10}{2} = 10$$

In [23]:
# execute backward
o.backward()

In [25]:
# calculate gradient
x.grad

tensor([10., 10.])